import { ComponentToken } from "antd/es/button/style";

const buttonLightTheme: ComponentToken = {
    fontWeight: '500',
    defaultShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    primaryShadow: '0 2px 8px rgba(74, 144, 226, 0.2)',
    dangerShadow: '0 2px 8px rgba(220, 53, 69, 0.2)',
    primaryColor: '#ffffff',
    defaultColor: '#4a90e2',
    defaultBg: '#f0f0f0',
    defaultBorderColor: '#d9d9d9',
    dangerColor: '#ffffff',
    defaultHoverBg: '#e6f7ff',
    defaultHoverColor: '#40a9ff',
    defaultHoverBorderColor: '#91d5ff',
    defaultActiveBg: '#d9f7be',
    defaultActiveColor: '#52c41a',
    defaultActiveBorderColor: '#b7eb8f',
    borderColorDisabled: '#d9d9d9',
    defaultGhostColor: '#4a90e2',
    ghostBg: 'transparent',
    defaultGhostBorderColor: '#4a90e2',
    solidTextColor: '#ffffff',
    textTextColor: '#4a90e2',
    textTextHoverColor: '#40a9ff',
    textTextActiveColor: '#1890ff',
    paddingInline: '16px',
    paddingInlineLG: '24px',
    paddingInlineSM: '8px',
    paddingBlock: '8px',
    paddingBlockLG: '12px',
    paddingBlockSM: '4px',
    onlyIconSize: 20,
    onlyIconSizeLG: 24,
    onlyIconSizeSM: 16,
    groupBorderColor: '#d9d9d9',
    linkHoverBg: 'transparent',
    textHoverBg: 'rgba(0, 0, 0, 0.1)',
    contentFontSize: 14,
    contentFontSizeLG: 16,
    contentFontSizeSM: 12,
    contentLineHeight: 1.5,
    contentLineHeightLG: 1.5,
    contentLineHeightSM: 1.5,
};

const buttonDarkTheme: ComponentToken = {
    fontWeight: '500',
    defaultShadow: '0 2px 8px rgba(255, 255, 255, 0.15)',
    primaryShadow: '0 2px 8px rgba(255, 255, 255, 0.2)',
    dangerShadow: '0 2px 8px rgba(255, 0, 0, 0.2)',
    primaryColor: '#ffffff',
    defaultColor: '#4a90e2',
    defaultBg: '#1f1f1f',
    defaultBorderColor: '#444444',
    dangerColor: '#ffffff',
    defaultHoverBg: '#2b2b2b',
    defaultHoverColor: '#40a9ff',
    defaultHoverBorderColor: '#91d5ff',
    defaultActiveBg: '#3a3a3a',
    defaultActiveColor: '#52c41a',
    defaultActiveBorderColor: '#b7eb8f',
    borderColorDisabled: '#444444',
    defaultGhostColor: '#4a90e2',
    ghostBg: 'transparent',
    defaultGhostBorderColor: '#4a90e2',
    solidTextColor: '#ffffff',
    textTextColor: '#4a90e2',
    textTextHoverColor: '#40a9ff',
    textTextActiveColor: '#1890ff',
    paddingInline: '16px',
    paddingInlineLG: '24px',
    paddingInlineSM: '8px',
    paddingBlock: '8px',
    paddingBlockLG: '12px',
    paddingBlockSM: '4px',
    onlyIconSize: 20,
    onlyIconSizeLG: 24,
    onlyIconSizeSM: 16,
    groupBorderColor: '#444444',
    linkHoverBg: 'transparent',
    textHoverBg: 'rgba(255, 255, 255, 0.1)',
    contentFontSize: 14,
    contentFontSizeLG: 16,
    contentFontSizeSM: 12,
    contentLineHeight: 1.5,
    contentLineHeightLG: 1.5,
    contentLineHeightSM: 1.5,
};

export { buttonLightTheme, buttonDarkTheme };